#!/usr/bin/env python3
"""
Report Generator - Creates PDF compliance assessment reports.
"""

import argparse
import json
from datetime import datetime
from pathlib import Path

from jinja2 import Template


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 11pt; color: #333; margin: 40px; }
        .header { text-align: center; border-bottom: 3px solid #1a365d; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #1a365d; margin: 0; font-size: 24pt; }
        .header .meta { font-size: 10pt; color: #888; margin-top: 10px; }
        .summary { background: #f8f9fa; padding: 20px; border-left: 4px solid #1a365d; margin: 20px 0; }
        .score-grid { display: flex; gap: 15px; margin: 20px 0; }
        .score-card { flex: 1; text-align: center; padding: 15px; border-radius: 8px; }
        .score-card.primary { background: linear-gradient(135deg, #1a365d, #2c5282); color: white; }
        .score-card.green { background: #c6f6d5; color: #22543d; }
        .score-card.yellow { background: #feebc8; color: #744210; }
        .score-card.red { background: #fed7d7; color: #822727; }
        .score-card .value { font-size: 28pt; font-weight: bold; }
        .score-card .label { font-size: 9pt; text-transform: uppercase; }
        .section { margin: 30px 0; }
        .section h2 { color: #1a365d; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }
        .control { border: 1px solid #e2e8f0; border-radius: 6px; margin: 10px 0; padding: 15px; }
        .control-header { display: flex; justify-content: space-between; align-items: center; }
        .control-id { font-weight: bold; color: #1a365d; }
        .status { padding: 3px 10px; border-radius: 12px; font-size: 9pt; font-weight: bold; }
        .status.compliant { background: #c6f6d5; color: #22543d; }
        .status.partial { background: #feebc8; color: #744210; }
        .status.gap { background: #fed7d7; color: #822727; }
        .footer { text-align: center; font-size: 9pt; color: #888; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ framework_name }}</h1>
        <div>Compliance Assessment Report</div>
        <div class="meta">Client: {{ client_id }} | Date: {{ date }} | AI Consensus: {{ ai_severity }} ({{ ai_confidence }}% confidence)</div>
    </div>
    
    <div class="summary">
        <h2 style="margin-top: 0;">Executive Summary</h2>
        <p>Assessment of {{ total_controls }} controls against {{ framework_name }} ({{ framework_version }}).</p>
        
        <div class="score-grid">
            <div class="score-card primary">
                <div class="value">{{ ai_severity }}</div>
                <div class="label">AI Consensus</div>
            </div>
            <div class="score-card green">
                <div class="value">{{ compliant }}</div>
                <div class="label">Compliant</div>
            </div>
            <div class="score-card yellow">
                <div class="value">{{ partial }}</div>
                <div class="label">Partial</div>
            </div>
            <div class="score-card red">
                <div class="value">{{ gaps }}</div>
                <div class="label">Gaps</div>
            </div>
        </div>
    </div>
    
    <div class="section">
        <h2>Control Findings</h2>
        {% for finding in findings %}
        <div class="control">
            <div class="control-header">
                <span class="control-id">{{ finding.control_id }}</span>
                <span class="status {{ finding.preliminary_status.replace('potential_', '') }}">{{ finding.preliminary_status.replace('potential_', '') }}</span>
            </div>
            <div style="margin-top: 8px; font-size: 10pt; color: #666;">{{ finding.control_name }}</div>
            {% if finding.evidence_found %}
            <div style="margin-top: 8px; font-size: 9pt;">Evidence: {{ finding.evidence_found | join(', ') }}</div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    
    <div class="footer">
        <p>Generated by IronClad Compliance | Iron City IT Advisors<br>Powered by AI Consensus Engine (15 models)</p>
    </div>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--template", help="Custom template (optional)")
    parser.add_argument("--output", required=True)
    parser.add_argument("--client-id", required=True)
    parser.add_argument("--framework", required=True)
    args = parser.parse_args()
    
    with open(args.input) as f:
        data = json.load(f)
    
    # Get AI consensus if present
    ai_consensus = data.get("ai_consensus", {})
    
    template_data = {
        "title": f"{data['framework']['name']} Assessment",
        "framework_name": data["framework"]["name"],
        "framework_version": data["framework"]["version"],
        "client_id": args.client_id,
        "date": datetime.now().strftime("%B %d, %Y"),
        "total_controls": data["preliminary_summary"]["total_controls"],
        "compliant": data["preliminary_summary"]["potential_compliant"],
        "partial": data["preliminary_summary"]["potential_partial"],
        "gaps": data["preliminary_summary"]["potential_gap"],
        "ai_severity": ai_consensus.get("severity", "PENDING"),
        "ai_confidence": ai_consensus.get("confidence", "N/A"),
        "findings": data["findings"]
    }
    
    template = Template(HTML_TEMPLATE)
    html = template.render(**template_data)
    
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    try:
        from weasyprint import HTML
        HTML(string=html).write_pdf(str(output_path))
        print(f"✅ PDF generated: {output_path}")
    except ImportError:
        html_path = output_path.with_suffix(".html")
        with open(html_path, "w") as f:
            f.write(html)
        print(f"⚠️ WeasyPrint unavailable, saved HTML: {html_path}")


if __name__ == "__main__":
    main()
